[project]
name = "tools-ipv6-split"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "ipy>=1.1",
    "plumbum>=1.9.0",
]
